name: Java CI - Checkout App

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      API_KEY_DEV: ${{ secrets.API_KEY_DEV }}
    steps:
    - name: Checkout código
      uses: actions/checkout@v4
      

    - name: Configurar JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Instalar dependencias y compilar
      run: mvn -B clean package --file pom.xml

    - name: Ejecutar pruebas unitarias
      run: mvn test -Dspring.profiles.active=test -DAPI_KEY_DEV=${{ secrets.API_KEY_DEV }}

    - name: Construir imagen Docker
      run: docker build -t checkout-app .

    - name: Verificar versión de Maven y Java
      run: |
        mvn -v
        java -version
